openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_0_1_1_homogeneisation_donnees_depenses.py
todo: handle gros postes 22, 45 and 99 which appear with this method
=> Deal with gros postes 10, 11 and 12

openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_01_consumption_by_categorie_fiscale.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_02_other_menage_variables.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_0_1_1_homogeneisation_donnees_depenses.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_0_1_2_imputations_loyers_proprietaires.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_0_3_homogeneisation_caracteristiques_menages.py
Tout ne tourne pas encore pour toutes les années
=> Some corrections

openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/run_all.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_0_1_1_homogeneisation_donnees_depenses.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_0_1_2_imputations_loyers_proprietaires.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_0_2_homogeneisation_vehicules.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_0_3_homogeneisation_caracteristiques_menages.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_0_4_homogeneisation_revenus_menages.py
Notamment la matrice de passage COICOP. J’envoie le nouveau fichier par
mail (à ranger dans le dossier adéquat).
=> WIP bdf 2011

openfisca_france_data/input_data_builders/build_openfisca_survey_data/step_02_imputation_loyer.py, openfisca_france_data/model/cotisations_sociales/travail.py
=> Fix important typo error in travail

openfisca_france_data/input_data_builders/build_openfisca_survey_data/step_05_foyer.py
Catégories ajoutées au dictionnaire :
6 Charges déductibles
7 réductions d’impôt
8 Divers
=> Boxes of the 2042 declaration for 2009 income tax

openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_03_calage.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_0_2_homogeneisation_vehicules.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_0_3_homogeneisation_caracteristiques_menages.py
Quelques petites corrections pour vérifier que tout se passe bien sur
ces années.
Todo: pareil pour les autres year_data
=> run_all working for year_data=2005 & year_calage in [2005-2009]

openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_01_consumption_by_categorie_fiscale.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_0_1_1_homogeneisation_donnees_depenses.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_0_1_2_imputations_loyers_proprietaires.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_0_2_homogeneisation_vehicules.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_0_3_homogeneisation_caracteristiques_menages.py
j'ai revu les todo dasn le code
de nomnbreux todo me semblent inutiles (des commentaires notamment)
faut-il les supprimer ?
=> checked the todo

openfisca_france_data/collection_builders/bdf_collection_builder.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/run_all.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_03_calage.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_0_1_2_imputations_loyers_proprietaires.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_0_2_homogeneisation_vehicules.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_0_3_homogeneisation_caracteristiques_menages.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_0_4_homogeneisation_revenus_menages.py
WIP le run_all 2000 à 2010 fonctionne, des bugs en train d'être corrigés pour 1995 et 2011
=> WIP run_all

openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/run_all.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_03_calage.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_0_1_1_homogeneisation_donnees_depenses.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_0_2_homogeneisation_vehicules.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_0_3_homogeneisation_caracteristiques_menages.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_0_4_homogeneisation_revenus_menages.py, openfisca_france_data/tests/test_yaml.py
j'ai corrigé le fichier revenu pour qu'il retourne bien le revenu disponible et donc le niveau de vie et donc les déciles
=> fixed revenus for graphs

openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/run_all.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_0_1_1_homogeneisation_donnees_depenses.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_0_1_2_imputations_loyers_proprietaires.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_0_2_homogeneisation_vehicules.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_0_3_homogeneisation_caracteristiques_menages.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_0_4_homogeneisation_revenus_menages.py
- j'ai enlevé le code stata qui a été traduit et qui n'ajoutait pas d'informations sur ce qui avait été fait
- j'ai ajouté des commentaires sur certaines étapes afin d'expliquer ce que l'on faisait (notamment exdep et exrev pour 1995)
Je pense que cela permet d'avoir plus rapidement une vue d'ensemble sur le travail de code et allège les fichiers
=> cleaning files (stata instructions) + comments (exdep exrev)

openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/run_all.py, openfisca_france_data/input_data_builders/build_openfisca_indirect_taxation_survey_data/step_03_calage.py
Le ratio de calage correspond avec celui calculé dans le rapport de Roy Dauvergne et permet également de trouver des taux d'effort plus crédibles.
=> calage des revenus

openfisca_france_data/model/calage.py, openfisca_france_data/reforms/inversion_directe_salaires.py
Je ne sais pas comment tester, mais je pense que certaines formules ne fonctionnait pas avant (elles utilisaient `quifam`)
=> Migrate formulas

.circleci/config.yml, .circleci/is-version-number-acceptable.sh, .circleci/publish-git-tag.sh, CHANGELOG.md, setup.py
To let the version checking script start to do its job.
=> Add automatic git tagging to CircleCI

CHANGELOG.md, openfisca_france_data/aggregates.py, openfisca_france_data/assets/zone_apl_data/codeAplReader.py, openfisca_france_data/assets/zone_apl_data/zone_apl/zone_apl_imputation_data_reader.py, openfisca_france_data/erfs/input_data_builder/run_all.py, openfisca_france_data/erfs/input_data_builder/step_02_imputation_loyer.py, openfisca_france_data/erfs/input_data_builder/step_05_foyer.py, openfisca_france_data/erfs/input_data_builder/step_07_invalides.py, openfisca_france_data/erfs/input_data_builder/step_08_final.py, openfisca_france_data/erfs/input_data_builder/step_10_check_final2.py, openfisca_france_data/erfs/old/aggregates.py, openfisca_france_data/erfs/old/datatable.py, openfisca_france_data/erfs_fpr/input_data_builder/step_02_imputation_loyer.py, openfisca_france_data/experimental_utils.py, openfisca_france_data/tests/erfs_fpr/test_af.py, openfisca_france_data/tests/erfs_fpr/test_impot_revenu.py, openfisca_france_data/tests/erfs_fpr/test_salaire_imposable.py, openfisca_france_data/tests/test_eipp.py, openfisca_france_data/tests/test_fake_survey_simulation.py, openfisca_france_data/tests/test_simulation.py, setup.py
- Change `print arg` to `print(arg)` for Python 3 compatibility
=> Fix syntax errors

CHANGELOG.md, setup.cfg, setup.py
- Limit code coverage to the `openfisca-france-data` package
=> Limit code coverage to package

CHANGELOG.md, setup.py
- Bump of `openfisca-france` to 34
=> Bump of OpenFisca-France to 34

CHANGELOG.md, openfisca_france_data/tests/base.py, openfisca_france_data/tests/test_simulation.py, setup.py
- Import `reduce` from `functools`
- It has been moved there in Python 3
=> Import reduce from functools

openfisca_france_data/tests/test_fake_survey_simulation.py
- Refactor and document a reform test
=> Fix test fake survey simulation

.circleci/config.yml, .circleci/has-functional-changes.sh, .circleci/is-version-number-acceptable.sh, .circleci/publish-git-tag.sh, .circleci/publish-python-package.sh, .editorconfig, CHANGELOG.md, Makefile, setup.cfg, setup.py
=> Deploy to PyPi

.editorconfig, CHANGELOG.md, openfisca_france_data/debugger.py, openfisca_france_data/erfs/__init__.py, openfisca_france_data/erfs/input_data_builder/step_05_foyer.py, openfisca_france_data/erfs/old/datatable.py, openfisca_france_data/erfs_fpr/input_data_builder/step_03_variables_individuelles.py, openfisca_france_data/reforms/inversion_directe_salaires.py, openfisca_france_data/surveys.py, openfisca_france_data/tests/test_fake_survey_simulation.py, openfisca_france_data/tests/test_simulation.py, openfisca_france_data/utils.py, setup.py
=> Replace .iteritems() with .items()

.circleci/has-functional-changes.sh, .gitignore
=> Ignore .mypy_cache/

CHANGELOG.md, openfisca_france_data/__init__.py, openfisca_france_data/assets/zone_apl_data/codeAplReader.py, openfisca_france_data/assets/zone_apl_data/zone_apl/zone_apl_imputation_data_reader.py, openfisca_france_data/erfs/input_data_builder/run_all.py, openfisca_france_data/erfs/input_data_builder/step_07_invalides.py, openfisca_france_data/erfs/input_data_builder/step_08_final.py, openfisca_france_data/erfs/input_data_builder/step_10_check_final2.py, openfisca_france_data/erfs/old/datatable.py, openfisca_france_data/erfs_fpr/get_survey_scenario.py, openfisca_france_data/surveys.py, openfisca_france_data/utils.py, setup.cfg, setup.py, tests/erfs_fpr/integration/test_af.py, tests/erfs_fpr/integration/test_rsa.py, tests/erfs_fpr/integration/test_salaire_imposable.py, tests/test_misc.py, tests/test_simulation.py
- Further cleanup
- Deprecation of `new_simulation_from_array_dict`
=> Further cleanup

CHANGELOG.md, openfisca_france_data/aggregates.py, openfisca_france_data/surveys.py, setup.py
- Adapt to [openfisca-survey-manager](https://github.com/openfisca/openfisca-survey-manager) v0.23
=> Rename weight column name

CHANGELOG.md, setup.py
=> Fix numpy deps

CHANGELOG.md, openfisca_france_data/__init__.py, openfisca_france_data/aggregates.py, openfisca_france_data/common.py, openfisca_france_data/dads/input_data_builder/create_variables_individuelles.py, openfisca_france_data/debugger.py, openfisca_france_data/erfs/input_data_builder/step_02_imputation_loyer.py, openfisca_france_data/erfs/input_data_builder/step_05_foyer.py, openfisca_france_data/erfs/old/datatable.py, openfisca_france_data/erfs_fpr/input_data_builder/step_03_variables_individuelles.py, openfisca_france_data/felin/input_data_builder/create_variables_individuelles.py, openfisca_france_data/model/common.py, openfisca_france_data/surveys.py, openfisca_france_data/utils.py, setup.py, tests/erfs_fpr/integration/test_af.py, tests/erfs_fpr/integration/test_aggregates.py, tests/erfs_fpr/integration/test_al.py, tests/erfs_fpr/integration/test_impot_revenu.py, tests/erfs_fpr/integration/test_salaire_imposable.py, tests/test_eipp.py
Merge using stuff from IPP CASD
=> Apply squased casd patches 2019 05 12

openfisca_france_data/erfs_fpr/input_data_builder/step_03_variables_individuelles.py, openfisca_france_data/erfs_fpr/input_data_builder/step_04_famille.py
=> Fix smic famille

CHANGELOG.md, openfisca_france_data/common.py, openfisca_france_data/dads/input_data_builder/create_variables_individuelles.py, openfisca_france_data/erfs_fpr/input_data_builder/step_03_variables_individuelles.py, openfisca_france_data/model/survey_variables.py, setup.py
- Introduce a new weight variable for households
- Update the SMIC parameter
=> Divers modifications

CHANGELOG.md, setup.py
Change the requirement version for OF-France
=> Change requirements versions OF-France

openfisca_france_data/erfs_fpr/input_data_builder/step_03_variables_individuelles.py, openfisca_france_data/smic.py
- Corrects a typo on smic_imposable to keep up with ipp's repo's evolution
=> corrects typo smic_imposable

.conda/meta.yaml, .gitlab-ci.yml, CHANGELOG.md, ci-runner/build_ci.py, ci-runner/empty_openfisca_erfs_fpr.json, setup.cfg, setup.py
- Improve GitLab CI:
- Add manual step to prevent execution of all years.
=> Speed up ci

README.md
- Add some useful install info for Windows users
=> Add Windows specificities to short install manual

CHANGELOG.md, openfisca_france_data/erfs_fpr/input_data_builder/step_06_final.py, setup.py
- Ajoute de deux jeux de données utilisées pour les tests au paquet : 
-  'assets/aggregats/taxipp/agregats_tests_taxipp_2_0.xlsx' 
- `'assets/aggregats/ines/ines_2019.json'
=> Ajoute les données d'agrégats dans le paquet

CHANGELOG.md, setup.py
- Update autopep8 and flake8 to make the requirements compatible with the latest versions of openfisca-france and openfisca-survey-manager
=> Aligne requirements sur france et survey-manager

CHANGELOG.md, openfisca_france_data/erfs_fpr/input_data_builder/step_04_famille.py, setup.py
- Corrige le calcul du smic annuel en fonction du smic horaire dans `openfisca_france_data/erfs_fpr/input_data_builder/step_04_famille.py`
=> Corrige la gestion des enfants majeurs dans la création des identifiants familles erfs-fpr

CHANGELOG.md, openfisca_france_data/__init__.py, openfisca_france_data/assets/aggregats/france_entiere/france_entiere_2019.json, openfisca_france_data/assets/aggregats/france_entiere/france_entiere_2020.json, openfisca_france_data/assets/aggregats/france_entiere/france_entiere_2021.json, openfisca_france_data/assets/aggregats/france_entiere/france_entiere_2022.json, openfisca_france_data/assets/aggregats/france_entiere/france_entiere_2023.json, openfisca_france_data/assets/aggregats/france_entiere/france_entiere_template.json, openfisca_france_data/assets/aggregats/ines/ines_2019.json, openfisca_france_data/assets/aggregats/ines/ines_2020.json, openfisca_france_data/erfs/__init__.py, openfisca_france_data/reforms/old_openfisca_france_reforms/cesthra_invalidee.py, setup.py, tests/erfs_fpr/integration/test_impot_revenu.py, tests/erfs_fpr/integration/test_pivot_table.py, tests/test_fake_survey_simulation.py
- Passage à Openfsca-France >= 155.0.0
=> Maj dependances

CHANGELOG.md, openfisca_france_data/felin/input_data_builder/create_variables_individuelles.py, setup.py
Correction parameters paths in function `create_taux_csg_remplacement`
=> Correction parameters (OF france) create_taux_csg_remplacement

CHANGELOG.md, setup.py
- Augmente la version d'openfisca-france exigée en dépendance
=> maj dépendance openfisca france

.github/workflows/workflow.yml, CHANGELOG.md, setup.py
- Change PyPi authentification to token to correct a publication issue
=> Move to Pypi token

CHANGELOG.md, setup.py
- Met à jour la version d'openfisca france dans les dépendances
=> update version d'openfisca france en dépendance

CHANGELOG.md, setup.py
- Met à jour la version d'openfisca france dans les dépendances
=> Update la version d'openfisca france

CHANGELOG.md, setup.py
- Met à jour la dépendance à OpenFisca France
=> upgrades packages

CHANGELOG.md, openfisca_france_data/pote/annualisation_variables.py, setup.py
- Adapte la réforme de POTE pour que les variables ne soient pas définies dans la classe
=> Adaptation tax benefit system POTE

CHANGELOG.md, openfisca_france_data/pote/annualisation_variables.py, setup.py
- Complète la réforme `AnnualisationVariablesIR` pour l'utilisation d'openfisca avec POTE
=> Ajout variables annuels pote

.github/workflows/workflow.yml, CHANGELOG.md, openfisca_france_data/erfs_fpr/input_data_builder/step_02_menage.py, openfisca_france_data/pote/input_data_builder/step_00_variables_pote.py, setup.py
- Modifie le loyer imputé pour avoir un montant annuel (solution temporaire compte tenu du manque de données sur les loyers après le millésime 2019 de l'ERFS)
=> Modifie le loyer imputé pour avoir un montant annuel

.gitlab-ci.yml, .gitlab-ci/all_years_build_and_aggregates.yml, .gitlab-ci/openfisca_survey_manager_raw_data.ini, CHANGELOG.md, openfisca_france_data/assets/aggregats/ines/ines_2022.json, openfisca_france_data/erfs_fpr/__init__.py, openfisca_france_data/erfs_fpr/input_data_builder/step_03_variables_individuelles.py, openfisca_france_data/erfs_fpr/input_data_builder/step_06_final.py, setup.py, tests/erfs_fpr/integration/test_aggregates.py
- Adapte le `build_input_data` de l'erfs-fpr pour qu'il fonctionne avec le millésime 2022
=> Erfs fpr 2022
