openfisca/openfisca-france-data

- openfisca_france_data/input_data_builders/build_openfisca_survey_data/step_01_pre_processing.py
- openfisca_france_data/input_data_builders/build_openfisca_survey_data/step_04_famille.py
- openfisca_france_data/input_data_builders/build_openfisca_survey_data/step_05_foyer.py
- openfisca_france_data/input_data_builders/build_openfisca_survey_data/step_06_rebuild.py
- openfisca_france_data/input_data_builders/build_openfisca_survey_data/step_07_invalides.py
- openfisca_france_data/input_data_builders/build_openfisca_survey_data/step_08_final.py
Reduce number of warning related to returning  view vs a copy issues by using .loc
(http://pandas.pydata.org/pandas-docs/stable/indexing.html#returning-a-view-versus-a-copy)
Results looks ok and test_agregates seams to return the same values has before, but this might need to be checked/compared more deeply.
Step_02 imputation has not been changed.
> remove warnings

- CHANGELOG.md
- openfisca_france_data/__init__.py
- openfisca_france_data/aggregates.py
- openfisca_france_data/assets/zone_apl_data/zone_apl/zone_apl_imputation_data_reader.py
- openfisca_france_data/debugger.py
- openfisca_france_data/erfs/input_data_builder/step_02_imputation_loyer.py
- openfisca_france_data/erfs/input_data_builder/step_03_fip.py
- openfisca_france_data/erfs/input_data_builder/step_05_foyer.py
- openfisca_france_data/erfs/input_data_builder/step_08_final.py
- openfisca_france_data/erfs/input_data_builder/step_10_check_final2.py
- openfisca_france_data/erfs_fpr/get_survey_scenario.py
- openfisca_france_data/erfs_fpr/input_data_builder/step_02_imputation_loyer.py
- openfisca_france_data/erfs_fpr/input_data_builder/step_03_variables_individuelles.py
- openfisca_france_data/model/calage.py
- openfisca_france_data/model/common.py
- openfisca_france_data/reforms/inversion_directe_salaires.py
- openfisca_france_data/tests/erfs_fpr/test_af.py
- openfisca_france_data/tests/erfs_fpr/test_aggregates.py
- openfisca_france_data/tests/erfs_fpr/test_al.py
- openfisca_france_data/tests/erfs_fpr/test_impot_revenu.py
- openfisca_france_data/tests/erfs_fpr/test_rebuild_input_data.py
- openfisca_france_data/tests/erfs_fpr/test_rsa.py
- openfisca_france_data/tests/erfs_fpr/test_salaire_imposable.py
- openfisca_france_data/tests/test_aggregates.py
- openfisca_france_data/tests/test_combining_reforms.py
- openfisca_france_data/tests/test_fake_survey_simulation.py
- setup.py
- Remove `__future__` imports
- They make sense no more as we've migrated to the Python 3 interpreter
> Remove __future__ expressions

- CHANGELOG.md
- Makefile
- openfisca_france_data/tests/test_aggregates.py
- openfisca_france_data/tests/test_calibration.py
- openfisca_france_data/tests/test_eipp.py
- openfisca_france_data/tests/test_inflation.py
- openfisca_france_data/tests/test_pivot_table.py
- openfisca_france_data/tests/test_simulation.py
- setup.cfg
- setup.py
- Replace `nosetests` (unmaintained) with `pytest`.
@benjello I did only adapt the tests you're **not** working on in #134, essentially the ones already excluded in `Makefile`.
This should be safe to merge.
> Use pytest

- CHANGELOG.md
- openfisca_france_data/aggregates.py
- openfisca_france_data/erfs/scenario.py
- openfisca_france_data/erfs_fpr/input_data_builder/__init__.py
- openfisca_france_data/surveys.py
- setup.py
- tests/conftest.py
- tests/erfs_fpr/integration/test_af.py
- tests/erfs_fpr/integration/test_al.py
- tests/erfs_fpr/integration/test_impot_revenu.py
- tests/erfs_fpr/integration/test_salaire_imposable.py
- tests/test_aggregate.py
- tests/test_calibration.py
- tests/test_combining_reforms.py
- tests/test_fake_survey_simulation.py
> Cleanup tests

- CHANGELOG.md
- openfisca_france_data/__init__.py
- openfisca_france_data/aggregates.py
- openfisca_france_data/debugger.py
- openfisca_france_data/erfs/input_data_builder/step_02_imputation_loyer.py
- openfisca_france_data/erfs/old/aggregates.py
- openfisca_france_data/erfs/old/datatable.py
- openfisca_france_data/erfs_fpr/get_survey_scenario.py
- openfisca_france_data/erfs_fpr/input_data_builder/__init__.py
- openfisca_france_data/erfs_fpr/input_data_builder/step_01_preprocessing.py
- openfisca_france_data/erfs_fpr/input_data_builder/step_02_imputation_loyer.py
- openfisca_france_data/erfs_fpr/input_data_builder/step_03_variables_individuelles.py
- openfisca_france_data/erfs_fpr/input_data_builder/step_04_famille.py
- openfisca_france_data/erfs_fpr/input_data_builder/step_05_final.py
- openfisca_france_data/erfs_fpr/scenario.py
- openfisca_france_data/model/calage.py
- openfisca_france_data/model/common.py
- openfisca_france_data/model/survey_variables.py
- openfisca_france_data/surveys.py
- openfisca_france_data/utils.py
- setup.py
- tests/erfs_fpr/integration/test_af.py
- tests/erfs_fpr/integration/test_aggregates.py
- tests/erfs_fpr/integration/test_al.py
- tests/erfs_fpr/integration/test_impot_revenu.py
- tests/erfs_fpr/integration/test_input_variables.py
- tests/erfs_fpr/integration/test_rebuild_input_data.py
- tests/erfs_fpr/integration/test_rsa.py
- Progress toward last version of openfisca-core, openfisca-france and openfisca-survey-manager
> Various improvements

- CHANGELOG.md
- openfisca_france_data/erfs_fpr/input_data_builder/__init__.py
- openfisca_france_data/erfs_fpr/input_data_builder/step_05_final.py
- setup.py
- Introduce `export_flattened_df` argument in `create_input_data_frame` function
- Allows for one `dummy_data.h5` file export that contains only one flattened table (one line per individual) instead of exporting an h5 file with several tables (one with individual and one for households). This fits better certain ways of importing back the data into openfisca (e.g. LexImpact).
- Upgrade `numexpr` top version to the version used by Core.
> Exports flattened output for erfs_fpr

- CHANGELOG.md
- setup.py
- Fix pypi upload by fixing package description
- [CircleCI](https://circleci.com/gh/openfisca/openfisca-france-data/663) error fixed: `The description failed to render in the default format of reStructuredText.`
> Fix pypi upload

- CHANGELOG.md
- openfisca_france_data/erfs_fpr/input_data_builder/__init__.py
- openfisca_france_data/erfs_fpr/input_data_builder/step_01_preprocessing.py
- openfisca_france_data/erfs_fpr/input_data_builder/step_04_famille.py
- setup.py
- Openfisca-france-data now handles more formats of the ERFS-FPR  (the files produced do not always have the exact same columns / column names)
> Erfs data improved

- CHANGELOG.md
- openfisca_france_data/erfs_fpr/input_data_builder/step_01_preprocessing.py
- openfisca_france_data/erfs_fpr/input_data_builder/step_03_variables_individuelles.py
- openfisca_france_data/smic.py
- setup.py
- Update openfisca-france dependency and fix parameters paths accordingly
- Rename `erfs_by_openfisca_variables` to `openfisca_by_erfs_variable`.
> Update openfisca-france dependency and fix parameters paths accordingly

- CHANGELOG.md
- openfisca_france_data/felin/input_data_builder/create_variables_individuelles.py
- setup.py
- Corrects two typos in the `create_taux_csg_remplacement` function used in the income inversion.
> corrige typo compute taux csg remplacement

- .conda/meta.yaml
- .gitlab-ci.yml
- CHANGELOG.md
- Makefile
- ci-runner/README.md
- ci-runner/build_ci.py
- ci-runner/openfisca_survey_manager_config.ini
- ci-runner/openfisca_survey_manager_raw_data.ini
- setup.cfg
- setup.py
- Remove Conda publish from Gitlab CI
- Put back all years in Gitlab CI
- Rename `runner` folder to `ci-runner` to be more explicit
Tested on Gitlab : https://git.leximpact.dev/benjello/openfisca-france-data/-/merge_requests/14
> Remove Conda publish from Gitlab-CI 

- CHANGELOG.md
- openfisca_france_data/model/common.py
- setup.py
Met à jour d'Openfisca-france, en corrigeant un problème
- dans model/common.py/salaire_brut:
- Retire rev_microsocial
rev_microsocial n'était pas un salaire mais un CA net des cotisations sociales pour les micro-entrepreneurs optant pour le versement libératoire de l'IR. Elle était donc à tort dans salaire_brut, d'autant plus qu'il n'y a pas d'autres rpns qui y sont répertoriés.
> Supprime rev_microsocial de salaire_brut

- CHANGELOG.md
- openfisca_france_data/comparator.py
- setup.py
> Improve comparator

- CHANGELOG.md
- setup.py
Mise à jour de Python à >=3.9, afin de permettre la compatibilité du package conda avec les dernières versions d'Openfisca-France.
> Mise à jour Python et OpenFisca-France

- CHANGELOG.md
- setup.py
- Déplace click dans les dépendances de test plutôt qu'install_requires
> Deplace dependance click vers test

- CHANGELOG.md
- openfisca_france_data/__init__.py
- openfisca_france_data/aggregates.py
- openfisca_france_data/erfs/input_data_builder/step_08_final.py
- openfisca_france_data/erfs/old/datatable.py
- openfisca_france_data/erfs/scenario.py
- openfisca_france_data/erfs_fpr/get_survey_scenario.py
- openfisca_france_data/erfs_fpr/scenario.py
- openfisca_france_data/model/common.py
- openfisca_france_data/model/survey_variables.py
- openfisca_france_data/surveys.py
- setup.py
- tests/conftest.py
- tests/erfs_fpr/integration/test_pivot_table.py
- tests/test_aggregate.py
- tests/test_calibration.py
- tests/test_fake_survey_simulation.py
- In _some module_:
- Remove…
- Introduce `some_function()`
- Allows for…
- Deprecate `some_function`.
- The functionality is now provided by…
- Rename `private_function`.
> Rebase refacto scenario

- CHANGELOG.md
- openfisca_france_data/utils.py
- setup.py
- Ajoute la possibilité de changer le tax and benefit system dans utils
L'utilisation prévue est pour Taxipp, où certaines variables de salaire doivent être récupérées à partir de Felin, pour compléter celles qui sont présentes dans les DADS. Comme il s'agit d'un cas assez particulier avec une définition de la variable `salaire_imposable ` spécifique (sans les revenus de l'étranger notamment, cases 1af et 1ag, mais en rajoutant notamment les revenus des gérants majoritaires 1gb) et en voulant la construire à partir des DADS, j'ai préféré permettre une utilisation plus souple d'openfisca-france-data (et sans aucune lourdeur supplémentaire a priori) plutôt que de construire dans openfisca-france des variables que nous serions les seuls à utiliser.
> Permet de modifier tax and benefit system dans utils

- CHANGELOG.md
- openfisca_france_data/erfs_fpr/input_data_builder/__init__.py
- openfisca_france_data/erfs_fpr/input_data_builder/step_03_variables_individuelles.py
- setup.py
- Améliore la construction des variables `contrat_de_travail` et `heures_remunerees_volumes` avec l'erfs_fpr
- Utilisations des variables `sp00` à `sp12` qui décrivent le statut d'activité sur les douze derniers mois pour prendre en compte la part de travail connue dans l'année
> Ameliore builder erfs fpr

- CHANGELOG.md
- openfisca_france_data/common.py
- openfisca_france_data/dads/input_data_builder/create_variables_individuelles.py
- setup.py
- tests/test_inversion.py
- Deprecate common.create_revenus_remplacement_bruts.
- The functionality is now provided by create_chomage_brut and create_retraite_brute
> Separe retraite et chômage

- .github/workflows/workflow.yml
- CHANGELOG.md
- openfisca_france_data/erfs_fpr/get_survey_scenario.py
- openfisca_france_data/pote/input_data_builder/console.py
- setup.py
- tests/pote/test_pote_survey_scenario.py
- Bump de la version d'openfisca-survey-manager en dépendances et adaptation du code à ce bump
> Upgrade openfisca survey manager
